application:
  name: demo_dev
  metadata: "develop"
  server:
    type: "fasthttp"
    address: ":8080"
    max_request_size: 2096157
    static:
      patten: "/"
      webroot: "./Static"
    jwt:
      header: "Authorization"
      secret: "12391JdeOW^%$#@"
      prefix: "Bearer"
      expires: 3
      enable: true
      skip_path: [
          "/info",
          "/v1/user/GetInfo"
      ]

